- name: Create Report Directory
  hosts: localhost
  gather_facts: no
  connection: local
  tasks:
    - name: Ensure Reports directories exist
      file:
         state: directory
         path: "{{ playbook_dir }}/reports/fragments/"

    - name: Ensure fragments directory is empty
      file:
         state: absent
         path: "{{ playbook_dir }}/reports/fragments/*"


- name: Install Windows Updates
  hosts: all
  serial: 1

  roles:
    - update-windows-jira


- name: Complete Report
  hosts: localhost
  gather_facts: no
  connection: local
  tasks:
    - name: Concat all the csv files 
      assemble: 
        src: "{{ playbook_dir }}/reports/fragments/"
        dest: "{{ playbook_dir }}/reports/updates.csv"

    - name: Append the header to the csv file 
      lineinfile: 
        dest: "{{ playbook_dir }}/reports/updates.csv"
        insertbefore: BOF 
        line: "Hostname,Rebooted,Found Updates,Installed Updates,Failed Updates,Installed KBs,Failed KBs" 

    - name: Mail Report
      mail:
        host: "{{ smpt_host }}"
        port: 25
        subject: Windows Update Report
        body: Windows Update Report
        from: "{{ from_email }}"
        to:
          - "{{ email }}"
        attach:
          - "{{ playbook_dir }}/reports/updates.csv"
